name: android build & deploy

on:
  #  workflow_dispatch:
  push:
    branches:
      # - master
      - feat
#  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.5'

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      - name: Set up key.properties
        run: |
          echo "Current Directory: $(pwd)"
          ls -la
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > flic.jks
          if [ -f "flic.jks" ]; then
              echo "flic.jks created successfully"
          else
              echo "Failed to create flic.jks"
              exit 1
          fi
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../../flic.jks" >> android/key.properties
          echo "Current Directory: $(pwd)"
          ls -la

      - name: Set up local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Set up Play Store Secret
        run: |
          echo "${{ secrets.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}" | base64 --decode > android/play_store_secret.json

      #  - name: Build & deploy Android release
      #    run: bundle exec fastlane android deploy
      #    env:
      #      KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
      #      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #      KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
      #      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      #      ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Build and Deploy
        run: |
          flutter pub get
          make deploy-android
